In [ ]:
wfung
rramirez

In [23]:
#1
import numpy as np
x = np.arange(19)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [25]:
#2
import numpy as np
x = np.arange(12)
grid = x.reshape(4,3)
print(grid)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [62]:
#3
import numpy as np

def ntimes(n):
    x = np.linspace(0 , 1 ,num=n)
    return(x)
y = ntimes(5)
print(y)

[ 0.    0.25  0.5   0.75  1.  ]


In [90]:
#4
import numpy as np
def gridntimes(a,b):
    x = np.arange((a*b))
    x = x.reshape(a,b)[0:4, 7:12]
    return(x)
axisX = int(input("insert x number: "))
axisY = int(input("insert y number: "))
y = gridntimes(axisX,axisY)
print(y)

insert x number: 20
insert y number: 55
[[  7   8   9  10  11]
 [ 62  63  64  65  66]
 [117 118 119 120 121]
 [172 173 174 175 176]]
